version: "3.8"

services:
  pt-accelerator:
    image: kowming/pt-accelerator:new
    container_name: pt-accelerator-new
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/hosts:/etc/hosts  #必须，用于 Hosts 联动功能
      - ./CFST:/app/CFST
      - ./config:/app/config
      - ./logs:/app/logs
      - ./cache:/app/cache
    environment:
      - TZ=Asia/Shanghai
      - APP_PORT=23333
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:$$APP_PORT/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
